insert into judokas (full_name, birth_date, belt, objectif) values
('BAERT PETIT Thaïs',       '2009-03-15', 'orange', 'Consolider mes projections de hanche'),
('BOUQUET Louis',            '2010-05-22', 'jaune',  'Obtenir ma ceinture orange'),
('BOYER Mathis',             '2007-11-08', 'verte',  'Travailler les techniques de jambes'),
('BREHERET Lise',            '2011-02-14', 'blanche','Maîtriser les chutes'),
('CHAUMAT Joachim',          '2005-07-30', 'bleue',  'Préparer la compétition régionale'),
('CLEMENT Elsa',             '2008-09-03', 'orange', 'Obtenir ma ceinture verte'),
('CLEMOT Lilian',            '2010-12-18', 'jaune',  'Progresser en ne-waza'),
('CLERGEOT Lucas',           '2006-04-25', 'verte',  'Maîtriser l''uchi-mata'),
('COMPOSTEL Marius',         '2003-08-11', 'marron', 'Préparer le 1er dan'),
('CORCELLE Arsène',          '2009-01-20', 'orange', 'Obtenir ma ceinture verte'),
('DE CUGNAC Wandrille',      '2012-06-07', 'blanche','Apprendre les bases du judo'),
('DE MARIA Maxence',         '2011-03-29', 'jaune',  'Obtenir ma ceinture orange'),
('DE SEVELINGES Côme',       '2007-10-14', 'verte',  'Progresser en compétition'),
('DE VALLAVIEILLE Joseph',   '2004-09-22', 'bleue',  'Préparer la ceinture marron'),
('DEROUET Yoran',            '2008-07-05', 'orange', 'Travailler le tai-otoshi'),
('DERUE Charles',            '2000-11-30', 'noire',  'Affiner ma pédagogie, préparer le 2e dan'),
('DIALLO Kadia',             '2010-04-17', 'jaune',  'Obtenir ma ceinture orange'),
('DUVOUX Hélène',            '2005-02-08', 'bleue',  'Me qualifier pour les championnats'),
('EMBRY Agathe',             '2012-09-11', 'blanche','Maîtriser les ukemi'),
('EPAILLY Samuel',           '2009-06-23', 'orange', 'Obtenir ma ceinture verte'),
('ERRAJI Oumnia',            '2010-01-16', 'jaune',  'Progresser en tachi-waza'),
('ETO''O NYEBE-CARRE Christine','2006-08-28','verte', 'Travailler les enchaînements debout-sol'),
('FERRY Lucile',             '2002-12-03', 'marron', 'Valider le 1er dan en fin de saison'),
('GAILLARD Lucie',           '2008-05-19', 'orange', 'Obtenir ma ceinture verte'),
('GERARDIN Flore',           '2012-03-07', 'blanche','Découvrir le judo'),
('GLORIEUX Eugénie',         '2011-07-24', 'jaune',  'Obtenir ma ceinture orange'),
('GUERLET Paul',             '2005-10-12', 'bleue',  'Préparer la ceinture marron'),
('GUERRA Jules',             '2009-08-31', 'orange', 'Maîtriser le harai-goshi'),
('HAMDI Kilian',             '2007-04-06', 'verte',  'Progresser en compétition junior'),
('HOSOE RIOS Jessica',       '2004-11-15', 'bleue',  'Me qualifier pour les championnats de France'),
('JOURD''HUI Arthur',        '2010-09-27', 'jaune',  'Progresser en ne-waza'),
('KALUZNY Nathan',           '2002-06-18', 'marron', 'Préparer le 1er dan'),
('LATANNE Bastien',          '2007-02-03', 'verte',  'Maîtriser les contres'),
('LUCAS Océane',             '2009-12-09', 'orange', 'Obtenir ma ceinture verte'),
('MOUCHON Pauline',          '2011-05-14', 'jaune',  'Apprendre l''ippon-seoi-nage'),
('PETITEAUX Nicolas',        '2001-09-08', 'marron', 'Valider le 1er dan cette saison'),
('PIGERON Lola',             '2007-07-21', 'verte',  'Préparer la ceinture bleue'),
('ROMAND Thomas',            '2005-03-16', 'bleue',  'Travailler l''uchi-mata et le ko-soto-gari'),
('ROUZE Anaïs',              '2012-10-30', 'blanche','Maîtriser les chutes'),
('SALVIAC Thomas',           '2008-11-04', 'orange', 'Travailler le sasae-tsuri-komi-ashi'),
('SANCHEZ Manon',            '2006-06-13', 'verte',  'Développer mon jeu au sol'),
('SCRIBE Isaac',             '2010-02-26', 'jaune',  'Obtenir ma ceinture orange'),
('SIBETH Athenaïs',          '2008-04-19', 'orange', 'Progresser en compétition'),
('STREPENNE Etoile',         '2012-08-02', 'blanche','Découvrir le judo'),
('THOBELLEM Emma',           '2011-01-11', 'jaune',  'Obtenir ma ceinture orange'),
('VAUDEVILLE Lucie',         '2006-09-28', 'verte',  'Maîtriser les étranglements'),
('YILDIZ Selin',             '2004-12-07', 'bleue',  'Préparer la ceinture marron');
